#! /bin/bash

python a2s_repetitions.py --model models/mutopia_ccal_cont_rsz_dense_att.py --config exp_configs/mutopia_full_aug_sc.yaml --train_split ../../msmd/msmd/splits/all_split.yaml --estimate_UV --piece BachJS__BWVAnh113__anna-magdalena-03 --audio_path repetitions/BachJS__BWVAnh113__anna-magdalena-03_tempo-1000_grand-piano-YDP-20160804_with1Repeats.wav
python a2s_repetitions.py --model models/mutopia_ccal_cont_rsz_dense_att.py --config exp_configs/mutopia_full_aug_sc.yaml --train_split ../../msmd/msmd/splits/all_split.yaml --estimate_UV --piece BachJS__BWVAnh113__anna-magdalena-03 --audio_path repetitions/BachJS__BWVAnh113__anna-magdalena-03_tempo-1000_grand-piano-YDP-20160804_with2Repeats.wav
python a2s_repetitions.py --model models/mutopia_ccal_cont_rsz_dense_att.py --config exp_configs/mutopia_full_aug_sc.yaml --train_split ../../msmd/msmd/splits/all_split.yaml --estimate_UV --piece BachJS__BWVAnh113__anna-magdalena-03 --audio_path repetitions/BachJS__BWVAnh113__anna-magdalena-03_tempo-1000_grand-piano-YDP-20160804_with3Repeats.wav

python a2s_repetitions.py --model models/mutopia_ccal_cont_rsz_dense_att.py --config exp_configs/mutopia_full_aug_sc.yaml --train_split ../../msmd/msmd/splits/all_split.yaml --estimate_UV --piece BachJS__BWVAnh120__BWV-120 --audio_path repetitions/BachJS__BWVAnh120__BWV-120_tempo-1000_ElectricPiano_1Repeats.wav
python a2s_repetitions.py --model models/mutopia_ccal_cont_rsz_dense_att.py --config exp_configs/mutopia_full_aug_sc.yaml --train_split ../../msmd/msmd/splits/all_split.yaml --estimate_UV --piece BachJS__BWVAnh120__BWV-120 --audio_path repetitions/BachJS__BWVAnh120__BWV-120_tempo-1000_ElectricPiano_2Repeats.wav
python a2s_repetitions.py --model models/mutopia_ccal_cont_rsz_dense_att.py --config exp_configs/mutopia_full_aug_sc.yaml --train_split ../../msmd/msmd/splits/all_split.yaml --estimate_UV --piece BachJS__BWVAnh120__BWV-120 --audio_path repetitions/BachJS__BWVAnh120__BWV-120_tempo-1000_ElectricPiano_3Repeats.wav
python a2s_repetitions.py --model models/mutopia_ccal_cont_rsz_dense_att.py --config exp_configs/mutopia_full_aug_sc.yaml --train_split ../../msmd/msmd/splits/all_split.yaml --estimate_UV --piece BachJS__BWVAnh120__BWV-120 --audio_path repetitions/BachJS__BWVAnh120__BWV-120_tempo-1000_ElectricPiano_4Repeats.wav

python a2s_repetitions.py --model models/mutopia_ccal_cont_rsz_dense_att.py --config exp_configs/mutopia_full_aug_sc.yaml --train_split ../../msmd/msmd/splits/all_split.yaml --estimate_UV --piece BachJS__BWVAnh131__air --audio_path repetitions/BachJS__BWVAnh131__air_tempo-1000_ElectricPiano_1Repeats.wav
python a2s_repetitions.py --model models/mutopia_ccal_cont_rsz_dense_att.py --config exp_configs/mutopia_full_aug_sc.yaml --train_split ../../msmd/msmd/splits/all_split.yaml --estimate_UV --piece BachJS__BWVAnh131__air --audio_path repetitions/BachJS__BWVAnh131__air_tempo-1000_ElectricPiano_2Repeats.wav
python a2s_repetitions.py --model models/mutopia_ccal_cont_rsz_dense_att.py --config exp_configs/mutopia_full_aug_sc.yaml --train_split ../../msmd/msmd/splits/all_split.yaml --estimate_UV --piece BachJS__BWVAnh131__air --audio_path repetitions/BachJS__BWVAnh131__air_tempo-1000_ElectricPiano_3Repeats.wav
python a2s_repetitions.py --model models/mutopia_ccal_cont_rsz_dense_att.py --config exp_configs/mutopia_full_aug_sc.yaml --train_split ../../msmd/msmd/splits/all_split.yaml --estimate_UV --piece BachJS__BWVAnh131__air --audio_path repetitions/BachJS__BWVAnh131__air_tempo-1000_ElectricPiano_4Repeats.wav

python a2s_repetitions.py --model models/mutopia_ccal_cont_rsz_dense_att.py --config exp_configs/mutopia_full_aug_sc.yaml --train_split ../../msmd/msmd/splits/all_split.yaml --estimate_UV --piece BachJS__BWVAnh691__BWV-691 --audio_path repetitions/BachJS__BWVAnh691__BWV-691_tempo-1000_ElectricPiano_1Repeats.wav
python a2s_repetitions.py --model models/mutopia_ccal_cont_rsz_dense_att.py --config exp_configs/mutopia_full_aug_sc.yaml --train_split ../../msmd/msmd/splits/all_split.yaml --estimate_UV --piece BachJS__BWVAnh691__BWV-691 --audio_path repetitions/BachJS__BWVAnh691__BWV-691_tempo-1000_ElectricPiano_2Repeats.wav
python a2s_repetitions.py --model models/mutopia_ccal_cont_rsz_dense_att.py --config exp_configs/mutopia_full_aug_sc.yaml --train_split ../../msmd/msmd/splits/all_split.yaml --estimate_UV --piece BachJS__BWVAnh691__BWV-691 --audio_path repetitions/BachJS__BWVAnh691__BWV-691_tempo-1000_ElectricPiano_3Repeats.wav
python a2s_repetitions.py --model models/mutopia_ccal_cont_rsz_dense_att.py --config exp_configs/mutopia_full_aug_sc.yaml --train_split ../../msmd/msmd/splits/all_split.yaml --estimate_UV --piece BachJS__BWVAnh691__BWV-691 --audio_path repetitions/BachJS__BWVAnh691__BWV-691_tempo-1000_ElectricPiano_4Repeats.wav
